/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useContext } from 'react';

export const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ko');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'ko' ? 'en' : 'ko'));
  };

  const t = (key, scope) => {
    const dict = translations[language] || translations['ko'];
    return dict[scope]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  ko: {
    nav: {
      about: '소개',
      history: '이력',
      apps: '앱',
      links: '링크',
      lang_toggle: '🇰🇷 한국어',
      theme_modern: '모던 테마',
      theme_retro: '레트로 테마',
      footer_company: '푸리에 소프트웨어 (Fourier Softwares)',
      footer_rep: '대표: 정진현 | 사업자등록번호: 559-59-00761',
      footer_email: '이메일: fourier.co.kr@gmail.com',
      footer_rights: 'Fourier Softwares. All rights reserved.'
    },
    home: {
      hello: "AI 자동화와 데이터 시스템을 구축하는\nB2B 소프트웨어 개발 파트너",
      role: "에이전틱 AI · 데이터 파이프라인 · 풀스택 외주 개발",
      desc: "푸리에 소프트웨어는 기업의 반복 업무, 흩어진 데이터, 오래된 시스템을 실제 운영 가능한 소프트웨어로 정리합니다. 에이전틱 AI 플랫폼, 대규모 데이터 파이프라인, 웹/앱 서비스를 요구사항 분석부터 구현, 배포, 운영 개선까지 작고 빠르게 완성합니다.",
      hero_primary_cta: "프로젝트 상담하기",
      hero_secondary_cta: "서비스 범위 보기",
      hero_proof_1: "기업 프로젝트 수행 경험",
      hero_proof_2: "AI·데이터·백엔드 통합 구현",
      hero_proof_3: "요구사항부터 배포까지 지원",
      proof_section_label: "푸리에 소프트웨어 신뢰 지표",
      proof_1_value: "Enterprise",
      proof_1_label: "SK Innovation, SK AX, LG유플러스 등 기업 환경 경험",
      proof_2_value: "Data + AI",
      proof_2_label: "검색엔진 전환, 데이터 거버넌스, AI 워크플로우 구현",
      proof_3_value: "End-to-End",
      proof_3_label: "분석, 설계, 구현, 배포, 운영 개선까지 연결",
      services_title: "외주로 맡기기 좋은 핵심 서비스",
      services_desc: "아이디어 단계의 상담부터 운영 중인 시스템 개선까지, 기업이 바로 써야 하는 결과물을 기준으로 범위를 정리합니다.",
      what_i_can_do: "무엇을 할 수 있나요",
      pipeline_title: "대규모 데이터 파이프라인 및 레거시 전환",
      pipeline_desc: "검색, 크롤링, 메타데이터, 메시징 데이터를 안정적으로 수집·정제·색인합니다. Solr/OpenSearch 전환, Elasticsearch 운영, Kafka/Redis/MongoDB 연동처럼 기존 시스템을 멈추지 않고 개선하는 작업에 강점이 있습니다.",
      fullstack_title: "B2B 웹 서비스 및 백엔드 개발",
      fullstack_desc: "관리자 포털, SaaS 기능, API 서버, 비동기 처리 시스템을 설계하고 구현합니다. React, Spring Boot, WebFlux, FastAPI 기반으로 트래픽과 운영 요구사항을 고려한 실무형 구조를 만듭니다.",
      agentic_ai_title: "에이전틱 AI 업무 자동화 플랫폼",
      agentic_ai_desc: "사내 문서, 업무 규칙, 외부 시스템을 연결해 조사, 분류, 보고, 승인 보조 같은 반복 업무를 자동화합니다. LangGraph, MCP, RAG, Human-in-the-loop 구조를 활용해 통제 가능한 기업용 AI 워크플로우를 설계합니다.",
      tech_stack: "사용가능 기술",
      process_title: "상담부터 구현까지의 흐름",
      process_desc: "처음부터 큰 계약을 전제로 하지 않고, 현재 문제와 우선순위를 확인한 뒤 실행 가능한 범위부터 제안합니다.",
      process_1_title: "문제와 목표 정리",
      process_1_desc: "현재 시스템, 반복 업무, 데이터 흐름, 만들고 싶은 기능을 간단히 확인합니다.",
      process_2_title: "범위와 기술 방향 제안",
      process_2_desc: "필요 기능, 예상 일정, 위험 요소, 우선순위를 정리해 현실적인 구현 범위를 잡습니다.",
      process_3_title: "작게 만들고 검증",
      process_3_desc: "핵심 기능부터 구현하고 실제 운영 흐름에 맞춰 개선합니다.",
      contact_title: "외주 개발 상담을 시작하세요",
      contact_desc: "AI 자동화, 데이터 파이프라인, 웹/앱 개발이 필요하다면 현재 상황과 목표만 간단히 남겨주세요. 가능한 범위, 일정, 기술 방향을 검토해 회신드립니다.",
      contact_cta: "상담 요청 보내기",
      contact_note: "회사명 또는 성함, 연락처, 만들고 싶은 내용을 남겨주시면 검토 후 연락드립니다.",
      request_modal_title: "프로젝트 상담 요청",
      request_modal_submit: "상담 요청 보내기",
      request_modal_cancel: "취소",
      request_modal_success: "문의가 접수되었습니다. 검토 후 빠르게 연락드리겠습니다.",
      request_modal_company: "회사명",
      request_modal_name: "성함",
      request_modal_phone: "핸드폰 번호",
      request_modal_email: "이메일",
      request_modal_type: "개발 타입",
      request_modal_type_placeholder: "개발 타입을 선택해주세요",
      request_modal_type_ai: "에이전틱 AI 플랫폼 구축",
      request_modal_type_data: "대규모 데이터 파이프라인 구축 및 레거시 데이터 변환",
      request_modal_type_fullstack: "Full Stack 개발 (Web/App)",
      request_modal_type_flutter: "Flutter 앱 개발 (Android)",
      request_modal_type_other: "기타",
      request_modal_content: "현재 상황, 만들고 싶은 기능, 희망 일정 또는 예산 범위를 적어주세요",
      flutter_title: "Flutter 모바일 앱 개발",
      flutter_desc: "Android 중심의 업무용 앱, 고객용 앱, MVP를 단일 코드베이스로 빠르게 구현합니다. 웹/백엔드 시스템과 연동되는 실사용 앱 개발에 맞춥니다.",
      game_title: "고성능 네트워크·엔진 개발 경험",
      game_desc: "게임 서버와 엔진 기반 개발 경험을 바탕으로 성능, 실시간 처리, 복잡한 상태 관리가 필요한 시스템에도 대응합니다.",
      frontend_title: "프론트엔드 개발",
      frontend_desc: "React, JavaScript 및 최신 CSS 기술을 사용하여 반응형이며 빠르고 아름다운 웹 인터페이스를 구축합니다.",
      opensource_title: "오픈소스 기여",
      opensource_desc: "다양한 오픈소스 게임 엔진과 프로젝트에 적극적으로 참여하고 기여합니다."
    },
    links: {
      title: "링크",
      ai_tab: "AI",
      opensource_tab: "오픈소스 경험",
      ai_category: "AI 및 에이전트 개발",
      ai_category_desc: "최근 관심이 높은 에이전틱 AI, RAG, 워크플로우 자동화, 도구 연동 생태계에서 실제 프로젝트 검토에 자주 쓰이는 링크입니다.",
      opensource_category: "경험 기반 오픈소스 프로젝트",
      opensource_category_desc: "지금까지 데이터 파이프라인, 검색엔진, 백엔드, 웹/앱 개발에서 다뤄온 오픈소스 기술을 분야별로 정리했습니다.",
      langchain_desc: "LLM 애플리케이션과 에이전트 워크플로우를 구성하는 대표 프레임워크",
      langgraph_desc: "상태 기반 멀티 에이전트와 장기 실행 워크플로우 설계에 적합한 그래프 런타임",
      llamaindex_desc: "문서, 데이터베이스, 사내 지식 기반 RAG 시스템 구축에 강한 데이터 프레임워크",
      mcp_desc: "AI 모델과 외부 도구, 데이터 소스를 표준 방식으로 연결하는 오픈 프로토콜",
      crewai_desc: "역할 기반 멀티 에이전트 팀을 빠르게 구성하고 실험하기 좋은 프레임워크",
      dify_desc: "RAG, 챗봇, 워크플로우를 포함한 LLM 앱 개발 플랫폼",
      n8n_desc: "업무 자동화와 외부 SaaS/API 연결에 강한 워크플로우 자동화 도구",
      flowise_desc: "LangChain 기반 AI 플로우를 시각적으로 구성하는 로우코드 빌더",
      search_data_category: "검색·데이터 파이프라인",
      backend_infra_category: "백엔드·인프라",
      app_framework_category: "웹·앱 프레임워크",
      opensearch_desc: "Solr/Elasticsearch 계열 검색 시스템 전환과 운영에 활용",
      elasticsearch_desc: "대규모 색인, 검색, 로그/데이터 분석 파이프라인에서 활용",
      solr_desc: "검색엔진 버전업, 성능 개선, OpenSearch 전환 경험 기반",
      monstache_desc: "MongoDB와 Elasticsearch/OpenSearch 간 실시간 동기화 구성에 활용",
      kafka_desc: "대규모 이벤트 스트리밍과 비동기 데이터 처리 파이프라인 구성",
      redis_desc: "캐시, 큐, 세션, 고속 데이터 접근 계층 구성",
      mongodb_desc: "메타데이터, 문서형 데이터, 서비스 백엔드 저장소로 활용",
      kubernetes_desc: "컨테이너 기반 서비스 운영과 배포 환경 구성",
      docker_desc: "서비스 패키징, 로컬 개발 환경, 배포 파이프라인 구성",
      react_desc: "B2B 관리자 포털과 프론트엔드 UI 구현",
      spring_boot_desc: "Java 기반 백엔드 API와 운영 서비스 개발",
      webflux_desc: "비동기·논블로킹 고성능 메시징/백엔드 처리",
      fastapi_desc: "Python 기반 API, 데이터 처리, AI 연동 서비스 개발",
      flutter_link_desc: "Android 중심 모바일 앱과 백엔드 연동 앱 개발",
      apps_title: "앱",
      android_apps: "안드로이드 앱",
      current_apps: "현재 서비스 중인 앱",
      kids_clock_genius: "키즈시계박사",
      future_apps: "출시 예정 앱",
      future_app_1: "출시 예정 앱 프로젝트 #1",
      game_projects: "게임 프로젝트 & 엔진",
      game_engines: "게임 엔진",
      tabs: {
        games: "게임",
        engines: "게임 엔진"
      },
      games_category: "오픈소스 게임",
      engines_category: "게임 엔진",
      zelda: "젤다의 전설 - 시간의 오카리나",
      zelda_desc: "시간의 오카리나 디컴파일 프로젝트",
      soh: "Ship of Harkinian",
      soh_desc: "libultraship 기반으로 개발되어 60FPS, 와이드스크린 등 현대적 편의 기능을 제공하는 PC 포트 프로젝트",
      pop: "페르시아의 왕자",
      pop_desc: "Apple II 원본 소스코드",
      abuse: "Abuse",
      abuse_desc: "Abuse (1996) 오픈소스"
    },
    history: {
      title: "이력 및 경험",
      desc: "다양한 도메인과 기술 환경에서 가치를 창출해 온 전문적인 실무 경력입니다.",
      total: "총",
      months: "개월",
      years: "년",
      under_1_month: "1개월 미만",
      present: "현재",
      freelance: "프리랜서",
      overseas: "🌎 해외 스타트업",
      clients: "고객사",
      shiftone_title: "시프트원주식회사",
      uplus_title: "유플러스 기업메시징",
      melchi_title: "(주)멸치",
      bilton_title: "㈜써머스플랫폼 (구 (주)빌트온)",
      gamera_title: "Gamera Networks",
      wonder_title: "(주)원더피플",
      hanbit_title: "(주)한빛소프트",
      hanbit_former: "(구 (주)조이임팩트)",
      gfzone_title: "(주)지에프존",
      skmns_title: "SK 엠앤서비스(주)",
      shiftone_desc: "Data Governance를 위한 포탈 및 메타데이터 관리 웹 애플리케이션 구축 및 운영",
      shiftone_b1: "Azure Cloud 환경에서의 인프라 운영 및 Azure Pipeline(K8s, Docker) 구축",
      shiftone_b2: "Spring Boot 및 Python을 활용한 데이터 거버넌스 백엔드 개발 및 유지보수",
      shiftone_b3: "PostgreSQL, MongoDB, Monstache, Redis를 활용한 이기종 데이터베이스 간 실시간 메타데이터 동기화 아키텍처 구현",
      uplus_desc: "다양한 타겟(문자메시지, RCS, 카카오톡 등)으로 메시지를 발송할 수 있는",
      uplus_desc_2: "서비스 구축 및 운영",
      uplus_b1: "MSA(Microservices Architecture) 구조를 채택하여 확장성 있는 백엔드 아키텍처 설계",
      uplus_b2: "Spring Boot 및 Spring WebFlux를 활용한 Reactive(비동기/논블로킹) 기반 고성능 메시지 처리 서비스 개발",
      uplus_b3: "대규모 트래픽 환경에서 안정적인 채널 연동 및 성능 최적화 진행",
      melchi_desc: "성능 저하 해소 및 고도화를 위한 검색엔진 마이그레이션 프로젝트 리딩 및 성공적 전환 완수",
      melchi_b1: "기존 Solr 검색엔진 버전업 및 성능 최적화 작업 수행",
      melchi_b2: "Solr 기반의 기존 검색엔진을 OpenSearch로 완전 전환 (설계 및 구축)",
      melchi_b3: "Java를 활용한 Oracle 및 PostgreSQL 데이터 색인(Indexing) 파이프라인 구축",
      melchi_b4: "Python을 활용한 검색 결괏값 도출 로직 및 API 연동",
      gamera_desc: "유저의 게임 플레이 화면을 녹화(FFmpeg 등 활용)하여 서버에 업로드하고 다른 유저들과 공유하는",
      gamera_desc_2: "앱 프로젝트의 Project Manager(PM) 및 백엔드 개발 수행",
      gamera_b1: "C++ 기반 영상 업로드 및 스트리밍 백엔드 서버 시스템 직접 설계 및 개발",
      gamera_b2: "Android 및 iOS 모바일 클라이언트 애플리케이션 개발 프로젝트 리드 및 매니징 (직접 개발 제외)",
      gamera_b3: "AWS 클라우드 인프라 아키텍처 구성 및 Linux 환경 최적화",
      bilton_desc: "수집엔진에서 수집된 크롤링 데이터를 가공 아키텍처 및 파이프라인 구축 및 개발",
      bilton_b1: "데이터 정제를 위한 Elasticsearch 적재 및 Data Mart 생성 파이프라인 구축",
      bilton_b2: "데이터 정제를 위한 소규모 스크립트 엔진 개발",
      bilton_b3: "TypeScript 및 DHTMLX를 활용한 데이터 정제 툴 개발",
      bilton_b4: "On-Premise 환경(CentOS) 서버 구축 및 MySQL 데이터베이스 운영",
      bilton_b5: "㈜써머스플랫폼 자회사로 편입된 후 최근 법인 폐업",
      hanbit_desc: "'스쿼드 플로우(Squad Flow)' 게임 서버 개발",
      hanbit_b1: "C++ 및 IOCP(I/O Completion Port)를 활용한 고성능 게임 서버 네트워크 로직 개발",
      hanbit_b2: "Windows Server 환경 구축 및 Microsoft SQL Server를 이용한 데이터베이스 설계",
      hanbit_b3: "(주)조이임팩트 입사 후, (주)한빛소프트로 자회사 흡수 합병됨에 따라 동일 프로젝트 지속 수행",
      wonder_desc: "동창 주소록 소셜 নে트워킹 앱 '멤버(Member)' 서버 개발",
      wonder_b1: "C++ 및 epoll을 활용한 고성능 Linux 기반 백엔드 네트워크 로직 개발",
      wonder_b2: "On-Premise 환경(Linux) 구축 및 MySQL을 이용한 데이터베이스 설계/운영",
      wonder_b3: "출시 후 iOS 앱스토어 및 Android 구글 플레이스토어 전체 앱 순위 1위 달성",
      gfzone_desc: "캐주얼 온라인 게임 '마경기담' 서버 개발",
      gfzone_b1: "C++ 및 IOCP를 활용한 고성능 Windows 기반 게임 서버 네트워크 프레임워크 개발",
      gfzone_b2: "Microsoft SQL Server를 이용한 데이터베이스 연동 및 쿼리 최적화",
      skmns_desc: "Tmap의 전신인 'Nate Drive' 및 '안전운전도우미' 피처폰 앱 개발",
      skmns_b1: "WIPI C 기술 기반 모바일 애플리케이션 개발",
      skmns_b2: "다양한 피처폰 기종 및 WIPI C 버전별 맞춤형 빌드 및 배포 파이프라인 운영"
    }
  },
  en: {
    nav: {
      about: 'About',
      history: 'History',
      apps: 'Apps',
      links: 'Links',
      lang_toggle: '🇺🇸 ENG',
      theme_modern: 'Modern Theme',
      theme_retro: 'Retro Theme',
      footer_company: 'Fourier Softwares',
      footer_rep: 'CEO: Jinhyun Jung | Business Reg. No.: 559-59-00761',
      footer_email: 'Email: fourier.co.kr@gmail.com',
      footer_rights: 'Fourier Softwares. All rights reserved.'
    },
    home: {
      hello: "B2B Software Partner for\nAI Automation and Data Systems",
      role: "Agentic AI · Data Pipelines · Full-Stack Delivery",
      desc: "Fourier Softwares turns repetitive operations, fragmented data, and legacy systems into production-ready software. We deliver agentic AI platforms, large-scale data pipelines, and web/app products from requirements analysis to implementation, deployment, and operational improvement.",
      hero_primary_cta: "Request a Project Consultation",
      hero_secondary_cta: "View Services",
      hero_proof_1: "Enterprise project delivery",
      hero_proof_2: "AI, data, and backend integration",
      hero_proof_3: "From requirements to deployment",
      proof_section_label: "Fourier Softwares proof points",
      proof_1_value: "Enterprise",
      proof_1_label: "Experience in SK Innovation, SK AX, LG U+, and other business environments",
      proof_2_value: "Data + AI",
      proof_2_label: "Search migration, data governance, and AI workflow implementation",
      proof_3_value: "End-to-End",
      proof_3_label: "Analysis, design, implementation, deployment, and operational improvement",
      services_title: "Core Services Built for Outsourcing",
      services_desc: "From early consultation to improving live systems, we define scope around deliverables your business can actually use.",
      what_i_can_do: "What I Can Do",
      pipeline_title: "Data Pipelines and Legacy Data Modernization",
      pipeline_desc: "We collect, clean, index, and synchronize search, crawling, metadata, and messaging data reliably. Our strength is improving existing systems without disruption, including Solr-to-OpenSearch migration, Elasticsearch operations, and Kafka, Redis, and MongoDB integrations.",
      fullstack_title: "B2B Web Services and Backend Development",
      fullstack_desc: "We design and build admin portals, SaaS features, API servers, and asynchronous processing systems. With React, Spring Boot, WebFlux, and FastAPI, we create practical architectures shaped around traffic, maintainability, and operations.",
      agentic_ai_title: "Agentic AI Workflow Automation",
      agentic_ai_desc: "We connect internal documents, business rules, and external systems to automate research, classification, reporting, and approval-support workflows. Using LangGraph, MCP, RAG, and human-in-the-loop patterns, we design AI workflows that remain controllable in enterprise environments.",
      tech_stack: "Tech Stack",
      process_title: "From Consultation to Delivery",
      process_desc: "We start with the current problem and priorities, then propose a practical scope before moving into implementation.",
      process_1_title: "Clarify the Problem",
      process_1_desc: "We review your current system, repeated work, data flow, and desired features.",
      process_2_title: "Define Scope and Direction",
      process_2_desc: "We outline required features, timeline, risks, priorities, and a realistic technical path.",
      process_3_title: "Build Small and Validate",
      process_3_desc: "We implement the core workflow first, then improve it against real operational needs.",
      contact_title: "Start a Development Consultation",
      contact_desc: "Tell us briefly about your current situation and goal for AI automation, data pipelines, or web/app development. We will review the scope, timeline, and technical direction and get back to you.",
      contact_cta: "Send Consultation Request",
      contact_note: "Share your company or name, contact details, and what you want to build. We will review it and reply.",
      request_modal_title: "Project Consultation Request",
      request_modal_submit: "Send Consultation Request",
      request_modal_cancel: "Cancel",
      request_modal_success: "Your request has been received. We will review it and contact you shortly.",
      request_modal_company: "Company Name",
      request_modal_name: "Name",
      request_modal_phone: "Phone Number",
      request_modal_email: "Email Address",
      request_modal_type: "Development Type",
      request_modal_type_placeholder: "Please select a development type",
      request_modal_type_ai: "Agentic AI Platform Construction",
      request_modal_type_data: "Large-scale Data Pipelines & Legacy Data Conversion",
      request_modal_type_fullstack: "Full Stack Development (Web/App)",
      request_modal_type_flutter: "Flutter App Development (Android)",
      request_modal_type_other: "Other",
      request_modal_content: "Describe your current situation, desired features, timeline, or budget range",
      flutter_title: "Flutter App Development",
      flutter_desc: "We build Android-focused business apps, customer apps, and MVPs from a single codebase, with particular care for integration with web and backend systems.",
      game_title: "High-Performance Network and Engine Experience",
      game_desc: "Our background in game servers and engine-based development supports systems that require performance, real-time processing, and complex state management.",
      frontend_title: "Frontend Development",
      frontend_desc: "Building responsive, fast, and beautiful web interfaces using React, JavaScript, and modern CSS.",
      opensource_title: "Open Source Contributions",
      opensource_desc: "Actively participating in and contributing to various open source game engines and projects."
    },
    links: {
      title: "Links",
      ai_tab: "AI",
      opensource_tab: "Open Source Experience",
      ai_category: "AI and Agent Development",
      ai_category_desc: "A curated set of links for agentic AI, RAG, workflow automation, and tool integration projects that are drawing strong developer attention.",
      opensource_category: "Open Source Projects I Have Worked With",
      opensource_category_desc: "Open source technologies I have used across data pipelines, search systems, backend services, and web/app development.",
      langchain_desc: "A leading framework for building LLM applications and agent workflows.",
      langgraph_desc: "A graph runtime for stateful multi-agent systems and long-running AI workflows.",
      llamaindex_desc: "A data framework for RAG systems built on documents, databases, and internal knowledge.",
      mcp_desc: "An open protocol for connecting AI models with external tools and data sources.",
      crewai_desc: "A framework for quickly designing role-based multi-agent teams.",
      dify_desc: "An LLM app platform covering RAG, chatbots, and workflow automation.",
      n8n_desc: "A workflow automation tool for connecting business systems, SaaS products, and APIs.",
      flowise_desc: "A low-code visual builder for LangChain-based AI flows.",
      search_data_category: "Search and Data Pipelines",
      backend_infra_category: "Backend and Infrastructure",
      app_framework_category: "Web and App Frameworks",
      opensearch_desc: "Used for search modernization and Solr/Elasticsearch-style search operations.",
      elasticsearch_desc: "Used in large-scale indexing, search, log, and data analysis pipelines.",
      solr_desc: "Experience with search engine upgrades, optimization, and migration to OpenSearch.",
      monstache_desc: "Used for real-time synchronization between MongoDB and Elasticsearch/OpenSearch.",
      kafka_desc: "Used for event streaming and asynchronous data processing pipelines.",
      redis_desc: "Used for caching, queues, sessions, and high-speed data access layers.",
      mongodb_desc: "Used for metadata, document data, and service backend storage.",
      kubernetes_desc: "Used for containerized service operations and deployment environments.",
      docker_desc: "Used for service packaging, local development, and deployment pipelines.",
      react_desc: "Used to build B2B admin portals and frontend interfaces.",
      spring_boot_desc: "Used for Java backend APIs and production services.",
      webflux_desc: "Used for async, non-blocking messaging and high-performance backend processing.",
      fastapi_desc: "Used for Python APIs, data processing, and AI-integrated services.",
      flutter_link_desc: "Used for Android-focused mobile apps connected to backend systems.",
      apps_title: "Apps",
      android_apps: "Android Apps",
      current_apps: "Current Apps",
      kids_clock_genius: "Kids Clock Genius",
      future_apps: "Future Apps",
      future_app_1: "Upcoming App Project #1",
      game_projects: "Game Projects & Engines",
      game_engines: "Game Engines",
      tabs: {
        games: "Games",
        engines: "Game Engines"
      },
      games_category: "Open Source Games",
      engines_category: "Game Engines",
      zelda: "The Legend of Zelda - Ocarina of Time",
      zelda_desc: "Ocarina of Time Decompilation Project",
      soh: "Ship of Harkinian",
      soh_desc: "An unofficial PC port built on libultraship, featuring 60FPS, widescreen, and modern enhancements.",
      pop: "Prince of Persia",
      pop_desc: "Apple II Original Source Code",
      abuse: "Abuse",
      abuse_desc: "Abuse (1996) Open Source"
    },
    history: {
      title: "History & Experience",
      desc: "A professional track record of delivering value across diverse domains and technology environments.",
      total: "Total",
      months: "mos",
      years: "yrs",
      under_1_month: "Less than 1 mo",
      present: "Present",
      freelance: "Freelance",
      overseas: "🌎 Overseas Startup",
      clients: "Clients",
      shiftone_title: "SHIFTONE Co., Ltd.",
      uplus_title: "U+ Enterprise Messaging",
      melchi_title: "Melchi",
      bilton_title: "Summerce Platform (Formerly BUILTON)",
      gamera_title: "Gamera Networks",
      wonder_title: "Wonder People Co., Ltd.",
      hanbit_title: "Hanbitsoft Inc.",
      hanbit_former: "(formerly JoyImpact)",
      gfzone_title: "GFZone",
      skmns_title: "SK m&service",
      shiftone_desc: "Built and operated a data governance portal and metadata management web application.",
      shiftone_b1: "Managed infrastructure in Azure Cloud and configured Azure Pipelines (K8s, Docker).",
      shiftone_b2: "Developed and maintained the Data Governance backend using Spring Boot and Python.",
      shiftone_b3: "Implemented a real-time metadata synchronization architecture across heterogeneous databases using PostgreSQL, MongoDB, Monstache, and Redis.",
      uplus_desc: "Built and operated a message delivery service for various targets (SMS, RCS, KakaoTalk) called",
      uplus_desc_2: "",
      uplus_b1: "Designed a scalable backend architecture utilizing MSA (Microservices Architecture).",
      uplus_b2: "Developed a high-performance reactive (async/non-blocking) messaging service using Spring Boot and Spring WebFlux.",
      uplus_b3: "Optimized performance and ensured stable channel integration in high-traffic environments.",
      melchi_desc: "Led and successfully completed a search engine migration project to resolve performance degradation.",
      melchi_b1: "Performed version upgrades and performance optimizations for the legacy Solr search engine.",
      melchi_b2: "Completely migrated the Solr-based search engine to OpenSearch (Design & Implementation).",
      melchi_b3: "Built a data indexing pipeline for Oracle and PostgreSQL using Java.",
      melchi_b4: "Implemented logic to derive search results and integrated APIs using Python.",
      gamera_desc: "Acted as Project Manager (PM) and Backend Developer for",
      gamera_desc_2: "an app where users record gameplay (using FFmpeg) and share it with others.",
      gamera_b1: "Directly designed and developed the C++ based video upload and streaming backend server system.",
      gamera_b2: "Managed and led the Android and iOS mobile client application development project (excluding direct development).",
      gamera_b3: "Configured AWS cloud infrastructure architecture and optimized the Linux environment.",
      bilton_desc: "Developed a system to process crawling data collected from the collection engine.",
      bilton_b1: "Loaded data into Elasticsearch for data refinement and created a Data Mart.",
      bilton_b2: "Developed a small-scale script engine for data refinement.",
      bilton_b3: "Developed a data refinement tool using TypeScript and DHTMLX.",
      bilton_b4: "Configured an On-Premise server environment (CentOS) and operated a MySQL database.",
      bilton_b5: "Acquired as a subsidiary by Summerce Platform, and recently closed down.",
      hanbit_desc: "Developed the game server for 'Squad Flow'",
      hanbit_b1: "Developed high-performance game server network logic using C++ and IOCP (I/O Completion Port).",
      hanbit_b2: "Configured a Windows Server environment and designed the database using Microsoft SQL Server.",
      hanbit_b3: "Joined JoyImpact, which was later absorbed by HanbitSoft, continuing the same project through the transition.",
      wonder_desc: "Developed the server for the alumni directory social networking app 'Member'",
      wonder_b1: "Developed high-performance Linux-based backend network logic using C++ and epoll.",
      wonder_b2: "Configured an On-Premise environment (Linux) and designed/operated the database using MySQL.",
      wonder_b3: "Achieved #1 overall ranking on both iOS App Store and Android Google Play Store after launch.",
      gfzone_desc: "Developed the server for the casual online game 'Magyeong Gidam'",
      gfzone_b1: "Developed a high-performance Windows-based game server network framework using C++ and IOCP.",
      gfzone_b2: "Integrated and optimized database queries using Microsoft SQL Server.",
      skmns_desc: "Developed feature phone apps 'Nate Drive' (predecessor to Tmap) and 'Safe Driving Assistant'",
      skmns_b1: "Developed mobile applications based on WIPI C technology.",
      skmns_b2: "Managed customized builds and deployment pipelines for various feature phone models and WIPI C versions."
    }
  }
};
